In [1]:
import sqlite3 as sql
import pandas as pd

In [2]:
#connection

conn = sql.connect('database.sqlite')
conn

In [3]:
a = conn.execute('select * from Salaries')
a

In [4]:
# function
def sql_query(q):
    return pd.read_sql_query(q,conn)

In [5]:
q = '''
select * from Salaries'''
sql_query(q)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,567595.43,567595.43,2011,,San Francisco,
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,,538909.28,538909.28,2011,,San Francisco,
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

##### 1. Top 10 highest paid employees (by TotalPayBenefits)

In [9]:
q = '''select EmployeeName, JobTitle, TotalPayBenefits
      from Salaries order by 3 DESC limit 10'''

sql_query(q)

,EmployeeName,JobTitle,TotalPayBenefits
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),538909.28
2,David Shinn,Deputy Chief 3,510732.68
3,Amy P Hart,Asst Med Examiner,479652.21
4,William J Coaker Jr.,Chief Investment Officer,436224.36
5,Gregory P Suhr,Chief of Police,425815.28
6,Joanne M Hayes-White,"Chief, Fire Department",422353.40
7,Gregory P Suhr,Chief of Police,418019.22
8,Joanne M Hayes-White,"Chief, Fire Department",417435.10
9,Ellen G Moffatt,Asst Med Examiner,415767.94

#### 2. Find which year has missing data of Employees with 'Not Provided'/ 'Not provided' .

In [11]:
q = '''SELECT Year, COUNT(*) AS Missing_Count
FROM Salaries
WHERE EmployeeName = 'Not Provided' OR EmployeeName = 'Not provided'
GROUP BY Year
ORDER BY Year'''
sql_query(q)

   Year  Missing_Count
0  2011              1
1  2012              1
2  2014              4

In [12]:
###3. Number of unique agencies

q = ''' select distinct agency from Salaries'''
sql_query(q)

          Agency
0  San Francisco

In [14]:
### 4 .Show Average BasePay, OvertimePay, and TotalPay for year 2011

q = ''' SELECT 
    AVG(BasePay) AS Avg_BasePay,
    AVG(OvertimePay) AS Avg_OvertimePay,
    AVG(TotalPay) AS Avg_TotalPay
FROM Salaries
WHERE Year = 2011'''

sql_query(q)

    Avg_BasePay  Avg_OvertimePay  Avg_TotalPay
0  63595.956517      4531.065429  71744.103871

In [16]:
### 5. Plot the top 10 job titles with the highest TotalPay in 2014.

q = '''SELECT JobTitle, SUM(TotalPay) AS TotalPay_Sum
FROM Salaries
WHERE Year = 2014
GROUP BY JobTitle
ORDER BY TotalPay_Sum DESC
LIMIT 10'''

sql_query(q)

                    JobTitle  TotalPay_Sum
0           Transit Operator  1.520080e+08
1           Registered Nurse  1.444065e+08
2                Firefighter  1.132836e+08
3           Police Officer 3  1.065347e+08
4             Deputy Sheriff  7.108394e+07
5                 Sergeant 3  6.084374e+07
6  Attorney (Civil/Criminal)  5.312390e+07
7             Police Officer  5.132217e+07
8              Special Nurse  4.949874e+07
9           Police Officer 2  4.631872e+07

In [23]:
#### 6. Which job titles have overtime pay exceeding $150,000 exluding 'Not provided'

q = '''SELECT DISTINCT JobTitle, OvertimePay
FROM Salaries
WHERE OvertimePay > 150000 AND JobTitle NOT IN ('Not Provided', 'Not provided')
ORDER BY OvertimePay DESC'''

sql_query(q)

                          JobTitle  OvertimePay
0  CAPTAIN III (POLICE DEPARTMENT)    245131.88
1     Lieutenant, Fire Suppression    220909.48
2                   Deputy Sheriff    196689.18
3        EMT/Paramedic/Firefighter    192424.49
4                   Deputy Sheriff    173547.73
5                   Deputy Sheriff    173178.23
6                   Deputy Sheriff    169659.92
7     Lieutenant, Fire Suppression    163477.81
8                      Firefighter    160418.47
9                   Deputy Sheriff    156077.49

In [32]:
### 7. Find all employees whose job titles contain the word “CHIEF”
q = '''
SELECT *
FROM Salaries
WHERE UPPER(JobTitle) LIKE '%CHIEF%'
'''
sql_query(q)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.00,182234.59,,326373.19,326373.19,2011,,San Francisco,
1,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602,8601.00,189082.74,,316285.74,316285.74,2011,,San Francisco,
2,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.90,134426.14,,315981.05,315981.05,2011,,San Francisco,
3,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,,303427.55,303427.55,2011,,San Francisco,
4,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262,0.00,17115.73,,302377.73,302377.73,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
622,138012,Sharon C Jackson,Chief Deputy Adlt Probation Of,56660.18,0.00,0.00,566.61,56660.18,57226.79,2014,,San Francisco,PT
623,139621,Anita S Lee,Chief Clerk,38598.86,0.00,0.00,386,38598.86,38984.86,2014,,San Francisco,PT
624,139710,George D Vaughan,Chief Nursery Specialist,27319.47,483.90,0.00,10334.67,27803.37,38138.04,2014,,San Francisco,PT
625,140081,Patrick W Gillespie,Chief Preparator,24091,0.00,0.00,10176.77,24091.00,34267.77,2014,,San Francisco,PT
626,140157,Christopher L Ochoa,Chief Stationary Engineer,24392,418.71,0.00,8918.44,24810.71,33729.15,2014,,San Francisco,PT

In [33]:
### 8. Count how many employees have job titles containing “ENGINEER” and “Fire” in year 2012 and 2013

q = '''
SELECT Year, COUNT(*) AS EmployeeCount
FROM Salaries
WHERE 
    (UPPER(JobTitle) LIKE '%ENGINEER%' OR UPPER(JobTitle) LIKE '%FIRE%')
    AND Year IN (2012, 2013)
GROUP BY Year'''
sql_query(q)

   Year  EmployeeCount
0  2012           2463
1  2013           2506

In [34]:
### 9. Distinct job titles starting with "CAPTAIN"

q = '''SELECT DISTINCT JobTitle
FROM Salaries
WHERE UPPER(JobTitle) LIKE 'CAPTAIN%'
'''
sql_query(q)

                                            JobTitle
0                    CAPTAIN III (POLICE DEPARTMENT)
1              CAPTAIN, EMERGENCYCY MEDICAL SERVICES
2                          CAPTAIN, FIRE SUPPRESSION
3  CAPTAIN, BUREAU OF FIRE PREVENTION AND PUBLIC ...
4                                          Captain 3
5                          Captain, Fire Suppression
6                        Captain, Emergency Med Svcs
7                         Captain, (Fire Department)

In [35]:
### 10. Employees having basepay > 50k and totalpay < 150000 exlucding 'Not Provided'

q = '''
SELECT *
FROM Salaries
WHERE 
    BasePay NOT IN ('Not Provided', 'not provided') AND
    TotalPay NOT IN ('Not Provided', 'not provided') AND
    CAST(BasePay AS FLOAT) > 50000 AND
    CAST(TotalPay AS FLOAT) < 150000'''

sql_query(q)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,2220,JAY DOWKE,POLICE OFFICER III,112380.37,15463.96,22142.91,,149987.24,149987.24,2011,,San Francisco,
1,2221,MURRAY BOND,MANAGER VI - MUNICIPAL TRANSPORTATION AGENCY,149975.80,0.00,0.00,,149975.80,149975.80,2011,,San Francisco,
2,2222,MARILOU GAN,REGISTERED NURSE,119703.78,8791.20,21475.87,,149970.85,149970.85,2011,,San Francisco,
3,2223,BRIAN COLLINS,FIREFIGHTER,105934.65,26506.04,17523.92,,149964.61,149964.61,2011,,San Francisco,
4,2224,GREGORY NEAL,POLICE OFFICER I,106065.20,14306.42,29580.85,,149952.47,149952.47,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
86650,138293,Renee J Allen,Special Nurse,52428.53,1029.78,0.00,534.59,53458.31,53992.90,2014,,San Francisco,PT
86651,138358,Melody M Butterworth,Attorney (Civil/Criminal),52389.79,0.00,165.65,525.55,52555.44,53080.99,2014,,San Francisco,PT
86652,138428,Stephanie Reidy,Special Nurse,51668.70,0.00,116.53,517.84,51785.23,52303.07,2014,,San Francisco,PT
86653,138480,Paul E Maltzer,Planner 5,51673.98,0.00,0.00,0,51673.98,51673.98,2014,,San Francisco,PT
86654,138525,Kathleen N Yumang,Special Nurse,50342.45,0.00,6.46,503.49,50348.91,50852.40,2014,,San Francisco,PT